# Generated by Django 3.1.3 on 2021-04-14 10:16

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('vehicle', '0001_initial'),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, null=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'cargo_type',
                'verbose_name_plural': 'cargo_types',
                'db_table': 'cargo_type',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Code')),
                ('active', models.BooleanField(default=True, null=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'task_status',
                'verbose_name_plural': 'task_statuses',
                'db_table': 'task_status',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, null=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'task_type',
                'verbose_name_plural': 'task_types',
                'db_table': 'task_type',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TransportationTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_from', models.CharField(blank=True, max_length=50, null=True, verbose_name='Location from')),
                ('location_to', models.CharField(blank=True, max_length=50, null=True, verbose_name='Location to')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='Date from')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Date to')),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Date to')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Price')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='Rating')),
                ('active', models.BooleanField(default=True, null=True, verbose_name='Active')),
                ('acceptor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transportation_task_acceptor', to='user.userprofile', verbose_name='Acceptor')),
                ('cargo_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.cargotype', verbose_name='Cargo type')),
                ('submitter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transportation_task_submitter', to='user.userprofile', verbose_name='Submitter')),
                ('task_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.taskstatus', verbose_name='Task status')),
                ('task_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.tasktype', verbose_name='Task type')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle.vehicle', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'transportation_task',
                'verbose_name_plural': 'transportation_tasks',
                'db_table': 'transportation_task',
                'ordering': ['date_from'],
            },
        ),
        migrations.CreateModel(
            name='StorageTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='Date from')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Date to')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Price')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='Rating')),
                ('active', models.BooleanField(default=True, null=True, verbose_name='Active')),
                ('acceptor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_task_acceptor', to='user.userprofile', verbose_name='Acceptor')),
                ('cargo_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.cargotype', verbose_name='Cargo type')),
                ('storage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.storage', verbose_name='Storage')),
                ('submitter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_task_submitter', to='user.userprofile', verbose_name='Submitter')),
                ('task_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.taskstatus', verbose_name='Task status')),
                ('task_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.tasktype', verbose_name='Task type')),
            ],
            options={
                'verbose_name': 'storage_task',
                'verbose_name_plural': 'storage_tasks',
                'db_table': 'storage_task',
                'ordering': ['date_from'],
            },
        ),
        migrations.CreateModel(
            name='ShippingTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_from', models.CharField(blank=True, max_length=50, null=True, verbose_name='Location from')),
                ('location_to', models.CharField(blank=True, max_length=50, null=True, verbose_name='Location to')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='Date from')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Date to')),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Date to')),
                ('cargo_weight', models.IntegerField(blank=True, null=True, verbose_name='Cargo weight')),
                ('cargo_dimensions', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cargo dimensions')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Price')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='Rating')),
                ('active', models.BooleanField(default=True, null=True, verbose_name='Active')),
                ('acceptor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_task_acceptor', to='user.userprofile', verbose_name='Acceptor')),
                ('cargo_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.cargotype', verbose_name='Cargo type')),
                ('submitter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_task_submitter', to='user.userprofile', verbose_name='Submitter')),
                ('task_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.taskstatus', verbose_name='Task status')),
                ('task_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.tasktype', verbose_name='Task type')),
                ('vehicle_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle.vehiclecategory', verbose_name='Vehicle category')),
            ],
            options={
                'verbose_name': 'shipping_task',
                'verbose_name_plural': 'shipping_tasks',
                'db_table': 'shipping_task',
                'ordering': ['date_from'],
            },
        ),
        migrations.CreateModel(
            name='TaskTypeTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='task.tasktype')),
            ],
            options={
                'verbose_name': 'task_type Translation',
                'db_table': 'task_type_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TaskStatusTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='task.taskstatus')),
            ],
            options={
                'verbose_name': 'task_status Translation',
                'db_table': 'task_status_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CargoTypeTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='task.cargotype')),
            ],
            options={
                'verbose_name': 'cargo_type Translation',
                'db_table': 'cargo_type_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
