# Generated by Django 3.1.3 on 2021-04-14 10:15

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, null=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'fuel type',
                'verbose_name_plural': 'fuel types',
                'db_table': 'fuel_type',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='VehicleBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Brand name')),
                ('active', models.BooleanField(default=True, null=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'vehicle brand',
                'verbose_name_plural': 'vehicle brands',
                'db_table': 'vehicle_brand',
            },
        ),
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, null=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'vehicle category',
                'verbose_name_plural': 'vehicle categories',
                'db_table': 'vehicle_category',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Model name')),
                ('active', models.BooleanField(default=True, null=True, verbose_name='Active')),
                ('vehicle_brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle.vehiclebrand', verbose_name='Vehicle brand')),
            ],
            options={
                'verbose_name': 'vehicle model',
                'verbose_name_plural': 'vehicle models',
                'db_table': 'vehicle_model',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(blank=True, max_length=11, null=True, verbose_name='VIN')),
                ('dimensions', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dimensions')),
                ('transport_capacity_kg', models.IntegerField(blank=True, null=True, verbose_name='Transport capacity (KG)')),
                ('transport_capacity_l', models.IntegerField(blank=True, null=True, verbose_name='Transport capacity (L)')),
                ('active', models.BooleanField(default=True, null=True, verbose_name='Active')),
                ('fuel_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle.vehiclebrand', verbose_name='Fuel type')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.userprofile', verbose_name='User')),
                ('vehicle_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle.vehiclecategory', verbose_name='Vehicle category')),
                ('vehicle_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle.vehiclemodel', verbose_name='Vehicle model')),
            ],
            options={
                'verbose_name': 'vehicle',
                'verbose_name_plural': 'vehicles',
                'db_table': 'vehicle',
            },
        ),
        migrations.CreateModel(
            name='VehicleCategoryTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('category_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Category name')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='vehicle.vehiclecategory')),
            ],
            options={
                'verbose_name': 'vehicle category Translation',
                'db_table': 'vehicle_category_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FuelTypeTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('fuel_type_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fuel type')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='vehicle.fueltype')),
            ],
            options={
                'verbose_name': 'fuel type Translation',
                'db_table': 'fuel_type_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
